export const GET_ALL_CHARACTERS         = 'GET_ALL_CHARACTERS';
export const GET_ALL_CHARACTERS_LOADING = 'GET_ALL_CHARACTERS_LOADING';
export const GET_ALL_CHARACTERS_ERROR   = 'GET_ALL_CHARACTERS_ERROR';

export const GET_DETAILS_CHARACTER         = 'GET_DETAILS_CHARACTER';
export const GET_DETAILS_CHARACTER_LOADING = 'GET_DETAILS_CHARACTER_LOADING';
export const GET_DETAILS_CHARACTER_ERROR   = 'GET_DETAILS_CHARACTER_ERROR';
